---
title: "Modeling IFT and Voulme Expansion"
output:
  github_document:
    pandoc_args: --webtex
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)

library(tidyverse, quietly = T)
library(broom, quietly = T)
library(tree, quietly = T)
library(readxl)
```

```{r load datasets for this lab, message=FALSE}
# let's us read the data set
ift_data <- read_excel(path = "data/ift_data.xlsx")
ift_data


```

```{r, warning=FALSE}
# visualizing the IFT
ggplot(ift_data, aes(Water_content, IFT,color = Gas) ) +
  geom_point() +
    ggtitle("Effect of water content and type of Gas in IFT")+

  stat_smooth()
```
```{r, warning=FALSE}
# visualizing the volume expansion
ggplot(ift_data, aes(Water_content, volume_ratio
                     ,color = Gas),
       ) +
  ggtitle("Effect of water content and type of Gas in Volume Ratio")+
  geom_point() +
  stat_smooth()
```

```{r}
# let's build a linear model to predict the IFT
model_ift <- lm(scale(IFT) ~ scale(Water_content)*scale(time_minutes), data = ift_data)
model_vol <- lm(volume_ratio ~ Water_content*time_minutes, data = ift_data)

```

```{r}
# IFT model
tidy(model_ift)
```
```{r}
# Volume Expansion model
tidy(model_vol)
```



